name: Coreferee Matrix Test
on: 
  workflow_dispatch:
  pull_request:

jobs:
  test-coreferee:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python_version: ['3.10', '3.11', '3.12', '3.13']
        spacy_version: ['3.8.16']
        click_version: ['8.5.0']
        include:
          - os: 'ubuntu-latest'
            python_version: '3.10'
            spacy_version: '3.7.5'
            click_version: '8.1.8'
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Initialize Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install spacy==${{ matrix.spacy_version }} pytest
        python -m pip install click==${{ matrix.click_version }}
        python -m pip check

    - name: Install spaCy models
      run: |
        python -m spacy download en_core_web_sm
        python -m spacy download en_core_web_md
        python -m spacy download en_core_web_lg
        python -m spacy download en_core_web_trf
        python -m spacy download de_core_news_sm
        python -m spacy download de_core_news_md
        python -m spacy download de_core_news_lg
        python -m spacy download fr_core_news_sm
        python -m spacy download fr_core_news_md
        python -m spacy download fr_core_news_lg
        python -m spacy download pl_core_news_md
        python -m spacy download pl_core_news_lg

    - name: Install Coreferee
      run: |
        cd ${{ github.workspace }}
        pip install .
        python -m coreferee install en
        python -m coreferee install de
        python -m coreferee install fr
        python -m coreferee install pl

    - name: Test Coreferee
      run: |
        python -m pytest tests/common
        python -m pytest tests/en
        python -m pytest tests/de
        python -m pytest tests/fr
        python -m pytest tests/pl